### ISSUE TITLE
`input_event` call fails while `CharacterBody3D` is moving

### ISSUE THREAD

**Issue by jrockett6** [godot-rust/gdext#267]
Node structure looks like this:

```rust
#[derive(GodotClass)]
#[class(init, base=CharacterBody3D)]
pub struct CharacterNode {
    #[base]
    base: Base<CharacterBody3D>,
}

#[godot_api]
impl CharacterBody3DVirtual for CharacterNode {
    fn input_event(
        &mut self,
        camera: Gd<Camera3D>,
        event: Gd<InputEvent>,
        position: Vector3,
        normal: Vector3,
        shape_idx: i64,
    ) { ... }
```

this intermittently throws the error (when the input_event is fired, e.g. when hovering over the body with the cursor):
```
thread '<unnamed>' panicked at 'Gd initialization failed; did you call share() on a dead instance?', /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:226:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:135:5
   3: core::panicking::panic_str
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:119:5
   4: core::option::expect_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:1879:5
   5: core::option::Option<T>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:741:21
   6: godot_core::obj::gd::Gd<T>::from_opaque
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:225:27
   7: godot_core::obj::gd::Gd<T>::from_obj_sys_weak
             at /Users/jrockett/workspace/3rd-party/gdext/godot-ffi/src/godot_ffi.rs:196:13
   8: godot_core::obj::gd::Gd<T>::from_obj_sys
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:431:9
   9: <godot_core::obj::gd::Gd<T> as godot_ffi::godot_ffi::GodotFfi>::from_arg_ptr
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:557:13
  10: godot_ffi::godot_ffi::scalars::<impl godot_ffi::godot_ffi::GodotFuncMarshal for T>::try_from_arg
             at /Users/jrockett/workspace/3rd-party/gdext/godot-ffi/src/godot_ffi.rs:477:16
  11: <(R,P0,P1,P2,P3,P4) as godot_core::builtin::meta::signature::SignatureTuple>::ptrcall_mut
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/builtin/meta/signature.rs:240:25
  12: <shared::combat::character::CharacterNode as godot_core::obj::traits::cap::ImplementsGodotVirtual>::__virtual_call::function
             at /Users/jrockett/workspace/isles_of_alcyon/shared/src/combat/character.rs:16:1
```

per [this](https://github.com/godot-rust/gdext/compare/master...lilizoey:gdextension:hotfix/type_name-in-gd-initialization-failure) change, we get a more descriptive error:
```
thread '<unnamed>' panicked at 'godot_core::obj::gd::Gd<godot_core::gen::classes::camera_3d::re_export::Camera3D> initialization failed; did you call share() on a dead instance?', /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:226:13
```

From my testing, this crashes consistently when the CharacterBody3D is moving (via `move_and_slide`). I have been unable to reproduce while the CharacterBody3D is stationary.

([relevant discord thread](https://discord.com/channels/723850269347283004/1043514894198255737/1105191823007305839))
OS: macOS Monterey 12.5, M1 2020
Godot Version: 4.0.1

**Comment by lilizoey** [comment]
For some reason we need to use `ref_get_object` here. why? i have no clue. im gonna investigate more.

**Comment by lilizoey** [comment]
this is caused by UB where we are receiving a `Camera3D**` pointer from godot but we interpret it as a `Camera3D*` pointer.
