### ISSUE TITLE
`ItemList::add_item` errors with somewhat unexpected "unimplemented" reference

### ISSUE THREAD

**Issue by bluenote10** [godot-rust/gdext#391]
Calling `ItemList::add_item` currently panics with `not implemented: see #156` referencing issue #156. However, at least on first glance, there is no obvious relation to that issue, and neither has the particular code that causes the panic:

https://github.com/godot-rust/gdext/blob/bb2be22f58b1418b6392107aac69e32aa0335c13/godot-codegen/src/util.rs#L574-L580

Is it possible that calling that function ends up in that particular panic just by accident, and the issue is actually something else?

A minimal reproduction project would be:

```rust
use godot::engine::{ItemList, NodeVirtual};
use godot::prelude::*;

struct ExtensionImpl;

#[gdextension]
unsafe impl ExtensionLibrary for ExtensionImpl {}

#[derive(GodotClass)]
#[class(base=Node)]
pub struct Ui {}

#[godot_api]
impl NodeVirtual for Ui {
    fn init(mut base: Base<Self::Base>) -> Self {
        let mut item_list = ItemList::new_alloc();
        item_list.add_item("foobar".into()); // panic here
        base.add_child(item_list.upcast());
        Self {}
    }
}
```

Or here as a small project: [ItemListPanic.zip](https://github.com/godot-rust/gdext/files/12448661/ItemListPanic.zip)

The full panic is:

<details>
<summary>Rust traceback</summary>

```
thread '<unnamed>' panicked at 'not implemented: see #156', /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/gen/classes/item_list.rs:1470:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: godot_core::gen::classes::item_list::ExAddItem::new
             at /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/gen/classes/item_list.rs:1470:42
   3: godot_core::gen::classes::item_list::re_export::ItemList::add_item_ex
             at /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/gen/classes/item_list.rs:151:13
   4: godot_core::gen::classes::item_list::re_export::ItemList::add_item
             at /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/gen/classes/item_list.rs:147:13
   5: <hello_world::Ui as godot_core::gen::classes::node::re_export::NodeVirtual>::init
             at ./rust/src/lib.rs:18:9
   6: <hello_world::Ui as godot_core::obj::traits::cap::GodotInit>::__godot_init
             at ./rust/src/lib.rs:13:1
   7: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
   8: godot_core::registry::callbacks::create_custom
             at /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/registry.rs:316:29
   9: godot_core::registry::callbacks::create
             at /home/fabian/.cargo/git/checkouts/gdext-76630c89719e160c/bb2be22/godot-core/src/registry.rs:299:9
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  16: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

</details>

Observed with the latest commit bb2be22f58b1418b6392107aac69e32aa0335c13 but also an earlier one.

**Comment by bluenote10** [comment]
After having a closer look, I think I see the connection to #156:

Godot's [`add_item`](https://docs.godotengine.org/en/stable/classes/class_itemlist.html#class-itemlist-method-add-item) function has the signature:

```
int add_item ( String text, Texture2D icon=null, bool selectable=true )
```

And it is probably the nullability of `icon` that leads to the same issue as in #156.

**Comment by Bromeon** [comment]
Since it looks like the same issue, I'd probably close this one? Maybe the title of the other one can be improved.

Btw, this just came up yesterday in Discord 🙂

**Comment by perry-blueberry** [comment]
I ran into the same issue recently with the same confusion about the message. One current workaround is to first set the icon an empty texture and then set the text (if you need the text):
```
let idx = self.base.add_icon_item(Texture2D::new());
self.base.set_item_text(idx, "text".into());
```

**Comment by Bromeon** [comment]
`Object::call()` with `Variant::nil()` might also be a possible workaround.

I updated the title in the other issue and added some landing-page description 😉
