### ISSUE TITLE
Can't compile gdext together with sqlx

### ISSUE THREAD

**Issue by RicardRC** [godot-rust/gdext#472]
Reproduction: (happens on windows and linux)
Go to master, dodge the screeps rust folder, overwrite the existing toml by this one, do a cargo build of dodge the screeps:
```
[package]
name = "dodge-the-creeps"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rand = "0.8"
sqlx = { version = "0.7.2" }
```
<details>
<summary>Build result:</summary>

```
cargo build
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling once_cell v1.18.0
   Compiling typenum v1.17.0
   Compiling godot4-prebuilt v0.0.0 (https://github.com/godot-rust/godot4-prebuilt?branch=4.1.1#fca6897d)
   Compiling windows_x86_64_msvc v0.48.5
   Compiling zerocopy v0.7.25
   Compiling unicode-segmentation v1.10.1
   Compiling serde v1.0.192
   Compiling allocator-api2 v0.2.16
   Compiling paste v1.0.14
   Compiling regex-syntax v0.8.2
   Compiling futures-core v0.3.29
   Compiling parking_lot_core v0.9.9
   Compiling nanoserde-derive v0.1.21
   Compiling tinyvec_macros v0.1.1
   Compiling scopeguard v1.2.0
   Compiling futures-task v0.3.29
   Compiling smallvec v1.11.2
   Compiling crossbeam-utils v0.8.16
   Compiling memchr v2.6.4
   Compiling futures-util v0.3.29
   Compiling percent-encoding v2.3.0
   Compiling equivalent v1.0.1
   Compiling cpufeatures v0.2.11
   Compiling futures-sink v0.3.29
   Compiling crossbeam-queue v0.3.8
   Compiling pin-project-lite v0.2.13
   Compiling futures-channel v0.3.29
   Compiling thiserror v1.0.50
   Compiling minimal-lexical v0.2.1
   Compiling unicode-bidi v0.3.13
   Compiling unicode_categories v0.1.1
   Compiling futures-io v0.3.29
   Compiling serde_json v1.0.108
   Compiling pin-utils v0.1.0
   Compiling crc-catalog v2.4.0
   Compiling log v0.4.20
   Compiling hex v0.4.3
   Compiling event-listener v2.5.3
   Compiling syn v1.0.109
   Compiling bytes v1.5.0
   Compiling ryu v1.0.15
   Compiling dotenvy v0.15.7
   Compiling byteorder v1.5.0
   Compiling getrandom v0.2.11
   Compiling tinyvec v1.6.0
   Compiling itoa v1.0.9
   Compiling tracing-core v0.1.32
   Compiling form_urlencoded v1.2.0
   Compiling godot-bindings v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling fastrand v2.0.1
   Compiling glam v0.23.0
   Compiling crc v3.0.1
   Compiling ppv-lite86 v0.2.17
   Compiling rand_core v0.6.4
   Compiling ahash v0.8.6
   Compiling generic-array v0.14.7
   Compiling lock_api v0.4.11
   Compiling num-traits v0.2.17
   Compiling slab v0.4.9
   Compiling godot-codegen v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling godot-macros v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling heck v0.4.1
   Compiling rand_chacha v0.3.1
   Compiling nom v7.1.3
   Compiling windows-targets v0.48.5
   Compiling nanoserde v0.1.35
   Compiling unicode-normalization v0.1.22
   Compiling windows-sys v0.48.0
   Compiling rand v0.8.5
   Compiling hashbrown v0.14.2
   Compiling quote v1.0.33
   Compiling godot-fmt v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling parking_lot v0.12.1
   Compiling syn v2.0.39
   Compiling venial v0.5.0
   Compiling idna v0.4.0
   Compiling regex-automata v0.4.3
   Compiling futures-intrusive v0.5.0
   Compiling hashlink v0.8.4
   Compiling indexmap v2.1.0
   Compiling tempfile v3.8.1
   Compiling url v2.4.1
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling digest v0.10.7
   Compiling atoi v2.0.0
   Compiling sha2 v0.10.8
   Compiling regex v1.10.2
   Compiling godot-ffi v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling godot-core v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)
   Compiling serde_derive v1.0.192
   Compiling thiserror-impl v1.0.50
   Compiling tracing-attributes v0.1.27
error: failed to run custom build command for `godot-core v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Ricard\Documents\gdext-master\target\debug\build\godot-core-671150f2722003af\build-script-build` (exit code: 101)
  --- stdout
  Parsed extension_api.json for version Header { version_major: 4, version_minor: 1, version_patch: 1, version_status: "stable", version_build: "official", version_full_name: "Godot Engine v4.1.1.stable.official" }
  -- add engine class AESContext  [renamed AesContext]
    -- inherits RefCounted

  --- stderr
  thread 'main' panicked at C:\Users\Ricard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.69\src\fallback.rs:817:9:
  "EnumAesContext.Mode" is not a valid Ident
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
     2: proc_macro2::fallback::is_ident_continue
     3: <proc_macro2::fallback::Group as core::fmt::Debug>::fmt
     4: <proc_macro2::fallback::Group as core::fmt::Debug>::fmt
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: quote::__private::mk_ident
     8: quote::__private::mk_ident
     9: godot_codegen::util::ident
    10: godot_codegen::TyName::from_godot
    11: godot_codegen::codegen_special_cases::is_method_excluded
    12: godot_codegen::codegen_special_cases::is_method_excluded::{{closure}}::{{closure}}
    13: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::any
    14: godot_codegen::codegen_special_cases::is_method_excluded::{{closure}}
    15: core::option::Option<T>::map_or
    16: godot_codegen::codegen_special_cases::is_method_excluded
    17: godot_codegen::special_cases::is_deleted
    18: <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next
    19: <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next
    20: godot_codegen::generate_core_files
    21: std::rt::lang_start
    22: std::rt::lang_start
    23: __ImageBase
    24: std::rt::lang_start
    25: std::rt::lang_start_internal::closure$2
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    26: std::panicking::try::do_call
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:502
    27: std::panicking::try
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:466
    28: std::panic::catch_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panic.rs:142
    29: std::rt::lang_start_internal
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    30: std::rt::lang_start
    31: main
    32: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    33: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    34: BaseThreadInitThunk
    35: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `godot-ffi v0.1.0 (https://github.com/godot-rust/gdext?branch=master#02f4acf5)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Ricard\Documents\gdext-master\target\debug\build\godot-ffi-b4ef4037961b6614\build-script-build` (exit code: 101)
  --- stdout
  Parsed extension_api.json for version Header { version_major: 4, version_minor: 1, version_patch: 1, version_status: "stable", version_build: "official", version_full_name: "Godot Engine v4.1.1.stable.official" }
  -- add engine class AESContext  [renamed AesContext]
    -- inherits RefCounted

  --- stderr
  thread 'main' panicked at C:\Users\Ricard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.69\src\fallback.rs:817:9:
  "EnumAesContext.Mode" is not a valid Ident
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
     2: proc_macro2::fallback::is_ident_continue
     3: proc_macro2::fallback::Group::set_span
     4: proc_macro2::fallback::Group::set_span
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: quote::__private::mk_ident
     8: quote::__private::mk_ident
     9: godot_codegen::util::ident
    10: godot_codegen::TyName::from_godot
    11: godot_codegen::codegen_special_cases::is_method_excluded
    12: godot_codegen::codegen_special_cases::is_method_excluded::{{closure}}::{{closure}}
    13: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::any
    14: godot_codegen::codegen_special_cases::is_method_excluded::{{closure}}
    15: core::option::Option<T>::map_or
    16: godot_codegen::codegen_special_cases::is_method_excluded
    17: godot_codegen::special_cases::is_deleted
    18: <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next
    19: <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next
    20: godot_codegen::generate_sys_files
    21: std::rt::lang_start
    22: std::rt::lang_start
    23: __ImageBase
    24: std::rt::lang_start
    25: std::rt::lang_start_internal::closure$2
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    26: std::panicking::try::do_call
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:502
    27: std::panicking::try
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:466
    28: std::panic::catch_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panic.rs:142
    29: std::rt::lang_start_internal
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    30: std::rt::lang_start
    31: main
    32: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    33: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    34: BaseThreadInitThunk
    35: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by Bromeon** [comment]
Your error message contains:
```
  "EnumAesContext.Mode" is not a valid Ident
```

which makes sense -- the `Ident` type can only accept real Rust identifiers, and this contains a dot.

I'm not sure if `sqlx` is actually related? What is the connection?

**Comment by RicardRC** [comment]
The only thing that points to sqlx <-> gdext interaction is the fact that I need to add the sqlx crate as toml dependency to trigger the bug, I have NO idea where does the bug come from, sorry :( .

**Comment by Bromeon** [comment]
Do you load any other Godot extensions besides gdext?

**Comment by RicardRC** [comment]
EnumAesContext does not yield any result on my machine either. I have tried with everything from the gdext book: prebuilt-bindings, nothing specified, and custom-godot, with all combinations of custom compiled and downloaded versions of godots versions 4.1.1, 4.1.2 and 4.1.3. Searching for only AESContext does yield results though. and that class does have a 
VARIANT_ENUM_CAST(AESContext::Mode); declared. So the missing EnumAesContext might come from some missing link between that class enum and the EnumAesContext it is looking for.

**Comment by Bromeon** [comment]
Looking at the stacktrace:
```
"EnumAesContext.Mode" is not a valid Ident
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
     ...
     9: godot_codegen::util::ident
    10: godot_codegen::TyName::from_godot
    11: godot_codegen::codegen_special_cases::is_method_excluded
    12: godot_codegen::codegen_special_cases::is_method_excluded::{{closure}}::{{closure}}
```

This seems to happen here:

https://github.com/godot-rust/gdext/blob/8ec6a229065396b209f14652334455c92063e342/godot-codegen/src/codegen_special_cases.rs#L57-L57

The code expects a class name, but we pass an enum name with a dot, which is not valid for the `Ident` type.

Fixing this would likely be a matter of recognizing non-class identifiers and not call `is_class_deleted` and `TyName::from_godot` in that case.

**Comment by RicardRC** [comment]
Here is a minimum reproduction case on a branch:
https://github.com/RicardRC/gdext/tree/472
To reproduce, just use "cargo build" on screeps in branch 472.

**Comment by RicardRC** [comment]
My best attempt so far: https://github.com/godot-rust/gdext/pull/579
