### ISSUE TITLE
Gd<XXX>.bind() cause crash, with `api-custom` feature in custom build godot.

### ISSUE THREAD

**Issue by tommyZZM** [godot-rust/gdext#755]
~~I m trying to write a custom plugin for godot in double precision build~~

~~Gd<XXX>.bind() cause crash, with double-precision feature in `double precision` build godot.~~ (Latest godot `master` branch)

Update the title... this issue is cause by the api-custom feature..

even i only just add `api-custom` the case crash too

Gd<XXX>.bind() cause crash, with `api-custom` feature in custom build godot...

But if same codes run in common build version it works fine

Maybe a minial reproduce case for this issue is here

https://github.com/tommyZZM/issue-cast-gd-pointer-crash-in-double-build/blob/main/rust/src/lib.rs#L95

```rust
if let Ok(mesh) = object.try_cast::<MyCustomMesh>() {
     // mesh.bind().size // crash by this
     godot_print!("size is {}", mesh.bind().size) // <-- crash this line
}
```

logs

```

thread '<unnamed>' panicked at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj:
Class issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh -- null instance; does the class have a Godot creator f?
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::resolve_instance_ptr<issu>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj\raw.rs:428
   3: godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::storage_unbounded<issue_c>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj\raw.rs:413
   4: godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::storage<issue_cast_gd_poi>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj\raw.rs:389
   5: godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::bind<issue_cast_gd_pointe>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj\raw.rs:370
   6: godot_core::obj::gd::Gd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::bind<issue_cast_gd_pointer_cr>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\obj\gd.rs:160
   7: issue_cast_gd_pointer_crash_in_double_build::impl$40::parse_begin
             at H:\WorkShop\_TEST\issue-cast-gd-pointer-crash-in-double-build\rust\src\lib.rs:95
   8: issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virtual_fn::closure$0
             at H:\WorkShop\_TEST\issue-cast-gd-pointer-crash-in-double-build\rust\src\lib.rs:83
   9: core::ops::function::FnOnce::call_once<issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virt:
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  10: godot_core::meta::signature::impl$18::in_ptrcall<tuple$<>,godot_core::obj::gd::Gd<godot_core::gen::classes::objec>
             at C:\Users\Mehere\.cargo\git\checkouts\gdext-76630c89719e160c\7eec09c\godot-core\src\meta\signature.rs:9
  11: issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virtual_fn
             at H:\WorkShop\_TEST\issue-cast-gd-pointer-crash-in-double-build\rust\src\lib.rs:83
  12: embree::TaskScheduler::wait
  13: embree::TaskScheduler::wait
  14: embree::TaskScheduler::wait
  15: embree::TaskScheduler::wait
  16: embree::TaskScheduler::wait
  17: embree::TaskScheduler::wait
  18: embree::TaskScheduler::wait
  19: embree::TaskScheduler::wait
  20: embree::TaskScheduler::wait
  21: embree::TaskScheduler::wait
  22: embree::TaskScheduler::wait
  23: <unknown>
  24: embree::TaskScheduler::wait
  25: embree::TaskScheduler::wait
  26: embree::TaskScheduler::wait
  27: embree::TaskScheduler::wait
  28: embree::TaskScheduler::wait
  29: <unknown>
  30: embree::TaskScheduler::wait
  31: embree::TaskScheduler::wait
  32: embree::TaskScheduler::wait
  33: embree::TaskScheduler::wait
  34: embree::TaskScheduler::wait
  35: embree::TaskScheduler::wait
  36: embree::TaskScheduler::wait
  37: embree::TaskScheduler::wait
  38: <unknown>
  39: <unknown>
  40: embree::TaskScheduler::wait
  41: embree::TaskScheduler::wait
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: embree::TaskScheduler::wait
  48: BaseThreadInitThunk
  49: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (5833f597865c773fae3ee09fc4e31d4a243f812d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] panic_unwind::__rust_start_panic (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\panic_unwind\src\lib.rs:1)
[4] std::panicking::rust_panic (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:831)
[5] std::panicking::rust_panic_with_hook (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:)
[6] std::panicking::begin_panic_handler::closure$0 (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\pan)
[7] std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$> ()
[8] std::panicking::begin_panic_handler (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:6)
[9] core::panicking::panic_fmt (/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72)
[10] godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::resolve_instance_ptr<issue)
[11] godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::storage_unbounded<issue_ca)
[12] godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::storage<issue_cast_gd_poin)
[13] godot_core::obj::raw::RawGd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::bind<issue_cast_gd_pointer)
[14] godot_core::obj::gd::Gd<issue_cast_gd_pointer_crash_in_double_build::MyCustomMesh>::bind<issue_cast_gd_pointer_cra)
[15] issue_cast_gd_pointer_crash_in_double_build::impl$40::parse_begin (H:\WorkShop\_TEST\issue-cast-gd-pointer-crash-i)
[16] issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virtual_fn::closure$0 (H:\WorkShop\_TEST\iss)
[17] core::ops::function::FnOnce::call_once<issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virtu)
[18] godot_core::meta::signature::impl$18::in_ptrcall<tuple$<>,godot_core::obj::gd::Gd<godot_core::gen::classes::object)
[19] issue_cast_gd_pointer_crash_in_double_build::impl$42::__virtual_call::virtual_fn (H:\WorkShop\_TEST\issue-cast-gd-)
[20] embree::TaskScheduler::wait
[21] embree::TaskScheduler::wait
[22] embree::TaskScheduler::wait
[23] embree::TaskScheduler::wait
[24] embree::TaskScheduler::wait
[25] embree::TaskScheduler::wait
[26] embree::TaskScheduler::wait
[27] embree::TaskScheduler::wait
[28] embree::TaskScheduler::wait
[29] embree::TaskScheduler::wait
[30] embree::TaskScheduler::wait
[31] <couldn't map PC to fn name>
[32] embree::TaskScheduler::wait
[33] embree::TaskScheduler::wait
[34] embree::TaskScheduler::wait
[35] embree::TaskScheduler::wait
[36] embree::TaskScheduler::wait
[37] <couldn't map PC to fn name>
[38] embree::TaskScheduler::wait
[39] embree::TaskScheduler::wait
[40] embree::TaskScheduler::wait
[41] embree::TaskScheduler::wait
[42] embree::TaskScheduler::wait
[43] embree::TaskScheduler::wait
[44] embree::TaskScheduler::wait
[45] embree::TaskScheduler::wait
[46] <couldn't map PC to fn name>
[47] <couldn't map PC to fn name>
[48] embree::TaskScheduler::wait
[49] embree::TaskScheduler::wait
[50] <couldn't map PC to fn name>
[51] <couldn't map PC to fn name>
[52] <couldn't map PC to fn name>
[53] <couldn't map PC to fn name>
[54] <couldn't map PC to fn name>
[55] embree::TaskScheduler::wait
[56] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by lilizoey** [comment]
exactly what godot version are you using, and what platform are you running on? i also notice you've enabled `experimental-wasm`, is this necessary?

**Comment by tommyZZM** [comment]
> godot version

latest godot `master` branch these days.

> i also notice you've enabled `experimental-wasm`, is this necessary

not nessary. I will try to remove it latter... I was just cpoyed the line from the exmple. Will this affect to this issue?

**Comment by tommyZZM** [comment]
https://github.com/godot-rust/gdext/blob/master/godot-core/src/registry/callbacks.rs#L67
```
fn create_rust_part_for_existing_godot_part<T, F>(
    make_user_instance: F,
    base_ptr: sys::GDExtensionObjectPtr,
) -> sys::GDExtensionClassInstancePtr
where
    T: GodotClass,
    F: FnOnce(Base<T::Base>) -> T,
{
    let class_name = T::class_name();

    //out!("create callback: {}", class_name.backing);

    let base = unsafe { Base::from_sys(base_ptr) }; // <--- base_ptr
```

https://github.com/godot-rust/gdext/blob/master/godot-core/src/obj/raw.rs#L426C66-L426C80
```
    unsafe fn resolve_instance_ptr(&self) -> sys::GDExtensionClassInstancePtr {
        if self.is_null() {
            return ptr::null_mut();
        }

        let callbacks = crate::storage::nop_instance_callbacks();
        let token = sys::get_library() as *mut std::ffi::c_void;
        let binding = interface_fn!(object_get_instance_binding)(self.obj_sys(), token, &callbacks); // self.obj_sys()

```

`base_ptr` and `self.obj_sys()` has a same address on common build godot.

but they have a different address in double-precision case

**Comment by lilizoey** [comment]
That's weird, we build against Godot master in CI, so this should be tested. What os are you on?

**Comment by tommyZZM** [comment]
Windows 10

**Comment by Bromeon** [comment]
> even i only just add `api-custom` the case crash too
> 
> [...]
> 
> Maybe a minial reproduce case for this issue is here

You mentioned just having the feature enabled reproduces it, however your example includes EditorPlugin etc.

Can you come up with a _truly_ minimal, reproducible example? If possible, post it inline here.

**Comment by tommyZZM** [comment]
`Godot 4.2.2` 

I tried to build a 4.2.2 rev of godot (`15073afe3856abd2aa1622492fe50026c7d63dc1`). But gdext master prompts error

```
[print_error] [panic]
  gdext was compiled against newer Godot version: v4.3.beta.custom_build
  but loaded by older Godot binary, with version: v4.2.2.stable.custom_build
```

But when I build the latest master branch(`8a6c1e8f5232ff3b3a5eac024d590e7479b29e90`), gdext currently doesn't seem to load correctly.

This is definitely probably some version difference

I think it might have something related to prebuilt?

**Comment by Bromeon** [comment]
Well, you cannot use a newer Godot version in `api-custom` than the binary in which you run the extension.

See https://godot-rust.github.io/book/toolchain/godot-version.html and https://godot-rust.github.io/book/toolchain/compatibility.html.

**Comment by tommyZZM** [comment]
When I want to build a double Godot, which commit rev should I build?

I tried adding the `api-4-2-2` feature, `features = ["api-4-2-2", "api-custom", "double-precision"]`

godot 4.2.2 `15073afe3856abd2aa1622492fe50026c7d63dc1` and latest gdext master rev `cd31a83d80edc7529ab2ef450d4c59d983913c19`

But after building and running, it still prompts error

```
[print_error] Rust function panicked at godot-ffi\src\compat\compat_4_1plus.rs:97.
Context: error when loading GDExtension library
[print_error] [panic]
gdext was compiled against newer Godot version: v4.3.beta.custom_build
but loaded by older Godot binary, with version: v4.2.2.stable.custom_build
```

**Comment by Bromeon** [comment]
Did you read my links? :wink:

**Comment by Bromeon** [comment]
@tommyZZM any update?

**Comment by tommyZZM** [comment]
> @tommyZZM any update?

i tried to build a godot 4.3 beta2

https://godotengine.org/article/dev-snapshot-godot-4-3-beta-2/#changelog

(https://github.com/godotengine/godot/commit/b75f0485ba15951b87f1d9a2d8dd0fcd55e178e4)

`scons platform=windows`

same crash still happen. what is latest compatible godot version for `api-custom` build?

**Comment by Bromeon** [comment]
> Can you come up with a _truly_ minimal, reproducible example? If possible, post it inline here.

**Please do this.** To avoid further back-and-forth, what I'm looking for is:
- A single `lib.rs` file that is self-contained and triggers the problem
- The exact Cargo commands you use to build
- The exact gdext and Godot versions (ideally both `master`, but maybe post commit SHA hashes)
- If there is any configuration or project/scene setup on Godot side **necessary** to trigger that, elaborate that.

Sorry if this sounds annoying, but the reason why I ask is that we have [a CI job](https://github.com/godot-rust/gdext/actions/runs/9839599377/job/27162015194) that runs on Windows with a Godot double configuration (from nightly master), and it just passed a few minutes ago. We definitely use `Gd::bind()` (in fact we run the whole integration test suite), and it doesn't crash. 

I need a way to reproduce this reliably and with as minimal setup as possible for the issue to stay open. Thanks a lot!

**Comment by tommyZZM** [comment]
> > Can you come up with a _truly_ minimal, reproducible example? If possible, post it inline here.
> 
> **Please do this.** To avoid further back-and-forth, what I'm looking for is:
> 
> * A single `lib.rs` file that is self-contained and triggers the problem
> * The exact Cargo commands you use to build
> * The exact gdext and Godot versions (ideally both `master`, but maybe post commit SHA hashes)
> * If there is any configuration or project/scene setup on Godot side **necessary** to trigger that, elaborate that.
> 
> Sorry if this sounds annoying, but the reason why I ask is that we have [a CI job](https://github.com/godot-rust/gdext/actions/runs/9839599377/job/27162015194) that runs on Windows with a Godot double configuration (from nightly master), and it just passed a few minutes ago. We definitely use `Gd::bind()` (in fact we run the whole integration test suite), and it doesn't crash.
> 
> I need a way to reproduce this reliably and with as minimal setup as possible for the issue to stay open. Thanks a lot!

Hello,

I have tried some examples, and I attempted to run the try_case and bind methods in the enter_tree of both Parent and Child nodes. It seems to work during runtime.

However, the same issue still appears in the example I initially provided. It might be that this problem only occurs with EditorInspectorPlugin, or it could be related to the editor itself.

```

use godot::prelude::*;
use godot::classes::{
    Node,
    INode,
    EditorInspectorPlugin, 
    EditorPlugin,
    EditorProperty, 
    IEditorInspectorPlugin, 
    IEditorPlugin
};

struct IssueReproduceExtensionLibrary;

#[gdextension]
unsafe impl ExtensionLibrary for IssueReproduceExtensionLibrary {}


#[derive(GodotClass)]
#[class(base=Node)]
pub struct MyNodeParent {
    pub base: Base<Node>,
    pub count: i32,
}

#[godot_api]
impl INode for MyNodeParent {
    // in editor created
    fn init(base: Base<Node>) -> Self {
        // godot_print!("init.. {}", !randInt!());
        godot_print!("init..");
        
        MyNodeParent {
            base, 
            count: 1
        }
    }

    fn enter_tree(&mut self) {
        godot_print!("enter_tree..");
        let child = Gd::from_init_fn(|base| {
            MyNodeChild { base }
        });
        self.base_mut().add_child(child.upcast());
    }
}

#[godot_api]
impl MyNodeParent {
    #[func]
    fn add(&mut self) {
        godot_print!("add...");
        self.count = self.count + 1
    }
}

#[derive(GodotClass)]
#[class(base=Node)]
pub struct MyNodeChild {
    pub base: Base<Node>
}

#[godot_api]
impl INode for MyNodeChild {
    // in editor created
    fn init(base: Base<Node>) -> Self {
        // godot_print!("init.. {}", !randInt!());
        godot_print!("init..");
        
        MyNodeChild {
            base
        }
    }

    fn enter_tree(&mut self) {
        let p = self.base_mut().get_parent().unwrap();
        let p_class: String = p.clone().get_class().to_string();
        godot_print!("[MyNodeChild]enter_tree.. parent is {}", p_class);

        if p_class == "MyNodeParent" {
            if let Ok(mut p_casted) = p.clone().try_cast::<MyNodeParent>() { // <-- this is OK
                let mut b = p_casted.bind_mut();
                b.add();
                godot_print!("size is {}", b.count)
            }
        } else {

        }
    }
}



#[derive(GodotClass)]
#[class(tool, init, editor_plugin, base=EditorPlugin)]
pub struct MyEditorPlugin {
  base: Base<EditorPlugin>,
  inspector_: Option<Gd<EditorInspectorPlugin>>
}

#[godot_api]
impl IEditorPlugin for MyEditorPlugin {
  fn enter_tree(&mut self) {
      godot_print!("enter_tree");
      // Perform typical plugin operations here.
      let inspector_ = Gd::from_init_fn(|base| {
            MyEdtiorInspectorPlugin { 
                base
            }
      }).clone();

      self.inspector_ = Some(inspector_.clone().upcast());

      self.base_mut().add_inspector_plugin(inspector_.clone().upcast());
  }

  fn exit_tree(&mut self) {
      // Perform typical plugin operations here.
      if let Some(ins) = self.inspector_.clone() {
          self.base_mut().remove_inspector_plugin(ins.clone())
      } else {
      }
  }
}

#[derive(GodotClass)]
#[class(tool, init, base=EditorInspectorPlugin)]
pub struct MyEdtiorInspectorPlugin{
    base: Base<EditorInspectorPlugin>,
}

#[godot_api]
impl IEditorInspectorPlugin for MyEdtiorInspectorPlugin {
    fn can_handle(&self, object: Gd<godot::classes::Object>) -> bool {
        let a: String = object.clone().get_class().to_string();

        let bool = a == "MyNodeParent";

        bool
    }

    fn parse_begin(&mut self, object: Gd<godot::classes::Object>,) {
        let a: String = object.clone().get_class().to_string();
        godot_print!("get_calss is {}", a);
        if let Ok(mut my_node_parent) = object.clone().try_cast::<MyNodeParent>() {
            godot_print!("cast ok {}", a);
            let my_node_parent_bind_mut = my_node_parent.bind(); // <-- error this line
            // ERROR: godot-rust function call failed: MyEdtiorInspectorPlugin::parse_begin()
            // Reason: [panic]  Class test_case::MyNodeParent -- null instance; does the class h?
            godot_print!("size is {}", my_node_parent_bind_mut.count) // <-- crash this line
        }
    }
}

```

**Comment by tommyZZM** [comment]
In the parse_begin method of EditorInspectorPlugin, when using custom-api, the object parameter seems unable to be correctly cast to the original object, resulting in a panic when calling bind. I tried printing the class name of the object, and it appears to be correct.

**Comment by Bromeon** [comment]
Thanks a lot. Since this is a bit more involved, it will take me some time until I can get around to try and reproduce it. In case you find a simpler way in the meantime (e.g. code only), let me know :slightly_smiling_face:

**Comment by Bromeon** [comment]
@tommyZZM it has been almost a year. In case you still use godot-rust, is this problem still occurring with latest `master`?

**Comment by Yarwin** [comment]
Isn't it related to https://github.com/godot-rust/gdext/issues/1132? I was able to reproduce the same case as in this issue – accidentally – while messing with editor plugin (now it should be OK, editor plugins are being added to tree AFTER all classes are registered)

**Comment by Yarwin** [comment]
Update – no, it is not related to aforementioned issue at all. It is related to placeholder instances and class not running in the editor. 

<details>

<summary> updated minimal reproduction </summary> 

```rs

struct IssueReproduceExtensionLibrary;

#[gdextension]
unsafe impl ExtensionLibrary for IssueReproduceExtensionLibrary {}

#[derive(GodotClass)]
// Doesn't run in editor!
#[class(base=MeshInstance3D)]
// #[class(tool, base=MeshInstance3D)]
pub struct MyCustomMesh {
    pub base: Base<MeshInstance3D>,

    #[export]
    size: i32,
}

#[godot_api]
impl IMeshInstance3D for MyCustomMesh {
    fn init(base: Base<MeshInstance3D>) -> Self {
        godot_print!("init..");

        MyCustomMesh { base, size: 1024 }
    }
}

#[derive(GodotClass)]
#[class(tool, init, base=EditorPlugin)]
pub struct MyEditorPlugin {
    base: Base<EditorPlugin>,
    inspector_1: Option<Gd<EditorInspectorPlugin>>,
}

#[godot_api]
impl IEditorPlugin for MyEditorPlugin {
    fn enter_tree(&mut self) {
        let inspector_1 = Gd::from_init_fn(|base| MyEdtiorInspectorPlugin { base }).clone();

        self.inspector_1 = Some(inspector_1.clone().upcast());

        self.base_mut()
            .add_inspector_plugin(&inspector_1);
    }

    fn exit_tree(&mut self) {
        let Some(ins) = self.inspector_1.clone() else {return;};
        self.base_mut().remove_inspector_plugin(&ins)
    }
}

#[derive(GodotClass)]
#[class(tool, init, base=EditorInspectorPlugin)]
pub struct MyEdtiorInspectorPlugin {
    base: Base<EditorInspectorPlugin>,
}

#[godot_api]
impl IEditorInspectorPlugin for MyEdtiorInspectorPlugin {
    fn can_handle(&self, object: Option<Gd<Object>>) -> bool {
        let Some(object) = object else {
            return false;
        };

        if object.is_class("MyCustomMesh") {
            godot_print!("object: {object}, class: {}, is_valid: {}", object.get_class(), object.is_instance_valid());
        }

        object.is_class("MyCustomMesh")
    }

    fn parse_begin(&mut self, object: Option<Gd<Object>>) {
        godot_print!("hello");
        let Some(object) = object else {
            return;
        };

        // Will never cause any crash. All the Godot classes run in the editor.
        // if let Ok(mesh) = object.try_cast::<MeshInstance3D>() {
        //     godot_print!("size is {}", mesh.get_custom_aabb())
        // }

        // Causes a crash if given object is non-tool Rust class
        if let Ok(mesh) = object.try_cast::<MyCustomMesh>() {
            godot_print!("size is {}", mesh.bind().size)
        }

    }
}
```

</details>

It no longer crashes the editor with the latest godot-rust, but errors at:

https://github.com/godot-rust/gdext/blob/080f12419620f4f9dd4e74e0940c51eb64c617a8/godot-core/src/obj/raw_gd.rs#L443-L447

<details> 

<summary> Image – editor error </summary>

![Image](https://github.com/user-attachments/assets/eacbb59e-0800-4807-a6de-616a27141144)

</details>

I won't include the whole stacktrace (available when one starts the editor with `RUST_BACKTRACE=1`), because it is too noisy.

~~Solution~~ Fix – make class a tool. 

<details> 

<summary> With `#[class(tool)]` </summary>

![Image](https://github.com/user-attachments/assets/1da28346-5651-46dd-96eb-cb8b112f2d6d)

</details>

The real solution – document it in https://godot-rust.github.io/docs/gdext/master/godot/classes/trait.IEditorInspectorPlugin.html.

**Comment by Bromeon** [comment]
Thanks so much for finding the root cause! :heart: 

While docs are good, I believe we should also improve the error message if anyhow possible. Is there a way we can detect this particular condition before it hits the general "null instance; ..." message?

If not, we could at least make that message include this potential cause.

**Comment by Yarwin** [comment]
> Does that mean it's _only_ valid to inherit `EditorInspectorPlugin` with the `#[class(tool)]` annotation? If yes, we could enforce that, maybe even at compile time 🤔 does it behave like [`EditorPlugin`](https://godot-rust.github.io/docs/gdext/master/godot/classes/struct.EditorPlugin.html) in that sense?

It is already enforced, albeit I'm not sure if it is required or not (I can check it while resolving TODO).

https://github.com/godot-rust/gdext/blob/adfd7fb496a655a5737ae2d01332e90ae40726fd/godot-macros/src/class/derive_godot_class.rs#L780-L792

But what I meant, the GDExtension class we are interacting with must be a tool – in this example it was `MyCustomMesh`. The base class (`MeshInstance3D`) can be accessed with no issues.


> While docs are good, I believe we should also improve the error message if anyhow possible. Is there a way we can detect this particular condition before it hits the general "null instance; ..." message? If not, we could at least make that message include this potential cause.

Sounds like good idea 👍. 
We can check if extension is loaded in editor or not (`crate::classes::Engine::singleton().is_editor_hint()`) and adjust the message accordingly. This is how Godot does it anyway https://github.com/godotengine/godot/pull/94511 (I should probably check if something changed since then)
