### ISSUE TITLE
To panic or not to panic when passing incorrect argument types?

### ISSUE THREAD

**Issue by andreymal** [godot-rust/gdext#845]
An example function:

```rust
#[derive(GodotClass)]
#[class(init)]
struct CallMe;

#[godot_api]
impl CallMe {
    #[func]
    fn call_me(a: Gd<Resource>, b: i32) -> Gd<Resource> {
        Resource::new_gd()
    }
}
```

These calls don't panic and abort the script instead:

```gdscript
# godot-rust function call failed / Bug, call error: #40

var not_a_resource: Variant = Node.new()
CallMe.call_me(not_a_resource, 0)

CallMe.call_me(null, 0)

var overflow_me_untyped: Variant = 9223372036854775807
CallMe.call_me(Resource.new(), overflow_me_untyped)
```

But these ones panic and **do not** abort the script (`null` is returned instead):

```gdscript
# godot-core/src/private.rs:369 - Rust function panicked at godot-core/src/meta/signature.rs:556.
#    Context: CallMe::call_me
#  godot-core/src/private.rs:382 - [panic]  in function `CallMe::call_me` at parameter [0] of type godot_core::obj::gd::Gd<godot_core::gen::classes::resource::re_export::Resource>: `Gd` cannot be null: null
var maybe_resource: Resource = null
CallMe.call_me(maybe_resource, 0)

# godot-core/src/private.rs:369 - Rust function panicked at godot-core/src/meta/signature.rs:556.
#    Context: CallMe::call_me
#  godot-core/src/private.rs:382 - [panic]  in function `CallMe::call_me` at parameter [1] of type i32: `i32` cannot store the given value: 9223372036854775807
var overflow_me_typed := 9223372036854775807
CallMe.call_me(Resource.new(), overflow_me_typed)
```

I don't know which behavior is correct (but according to [API design principles](https://godot-rust.github.io/book/contribute/philosophy.html#api-design-principles) <sub>(which contains a broken link btw)</sub> and https://github.com/godot-rust/gdext/issues/327#issuecomment-2097020581, I assume you are a fan of panics)

But regardless, I expect consistent behavior: panic everywhere or don't panic at all.

<sup>(In general, I'd prefer not to panic because I'm trying to compile with `panic = "abort"` in hopes of reducing binary size, godot-rust binaries are so damn huge...)</sup>
<sup><sub>(or maybe explicitly disallow `panic = "abort"` somewhere in the "Getting Started" chapter of the book if you think this sucks)</sub></sup>

**Comment by Bromeon** [comment]
> godot-rust binaries are so damn huge.

Try the `lazy-function-tables` feature, that should help. See lib.rs docs for explanation.

> panic = "abort"

You can try this, but I'm not sure how many things break in the library, as it's not designed for it. So use at your own risk.

**Comment by Bromeon** [comment]
After [some discussion](https://chat.godotengine.org/channel/gdextension?msg=2NzhMjdWKX4bA98H2) with the GDExtension team, it seems like the varcall error handling capability is _not_ intended for domain-specific errors (such as Rust panics), but rather type and arity checking of the arguments. 

If we handle Rust panics purely in Rust code and don't tap into the varcall error mechanism, we may be able to make the experience more consistent with ptrcalls.

Closely related: https://github.com/godot-rust/gdext/issues/105#issuecomment-2091840490

**Comment by andreymal** [comment]
> godot-rust binaries are so damn huge.

A bit off-topic here but I want to note somewhere that `handle_panic_with_print` is heavy, replacing its body with `return Ok(code());` made my test binary ~200KB smaller (~4KB per `#[func]`)

**Comment by Bromeon** [comment]
Any ideas on how to address this discrepancy?
We have a very similar issue here: https://github.com/godot-rust/gdext/issues/105#issuecomment-2091840490
