### ISSUE TITLE
Exporting an Array of an unexportable type panics in class registration

### ISSUE THREAD

**Issue by awsumpwner27** [godot-rust/gdext#870]
Godot Engine v4.3.stable.official; gdext latest master (7634fe7)
Example:
```rust
#[derive(GodotClass, Debug)]
#[class(init, base=Node)]
struct ExportingNode {
    // The following lines fail to compile with an error message suggesting the field isn't a type
    // that can be exported.
    // #[export]
    // cannot_export: Gd<CannotExport>,

    // This compiles but causes the extension to panic during class registration.
    #[export]
    cannot_export_array: Array<Gd<CannotExport>>,

    base: Base<Node>,
}

#[derive(GodotClass, Debug)]
#[class(init, base=RefCounted)]
struct CannotExport {
    base: Base<RefCounted>,
}
```
```
godot-core/src/private.rs:365 - Rust function panicked at godot-core/src/obj/gd.rs:761.
    Context: failed to initialize GDExtension level `Scene`
godot-core/src/private.rs:378 - [panic]  internal error: entered unreachable code: element_type_string() should only be invoked for exportable classes
godot-core/src/private.rs:365 - Rust function panicked at godot-core/src/registry/class.rs:207.
    Context: failed to initialize GDExtension level `Editor`
godot-core/src/private.rs:378 - [panic]  global lock for loaded classes poisoned; class registration or deregistration may have panicked
```

**Comment by lilizoey** [comment]
Should be a pretty simple fix, just adding a `where T: Export` to the array export impl
